using Blazor.NLDesignSystem.Extensions;

namespace Blazor.NLDesignSystem
{
    public enum Icon
    {
        Undefined,
        [Style("icon-arr-backward")]
        ArrowBackward,
        [Style("icon-arr-forward")]
        ArrowForward,
        [Style("icon-arrow-back")]
        ArrowBack,
        [Style("icon-cat-dummy")]
        CatDummy,
        [Style("icon-check")]
        Check,
        [Style("icon-chevron-down")]
        ChevronDown,
        [Style("icon-chevron-left")]
        ChevronLeft,
        [Style("icon-chevron-right")]
        ChevronRight,
        [Style("icon-chevron-up")]
        ChevronUp,
        [Style("icon-collapse-down")]
        CollapseDown,
        [Style("icon-collapse-left")]
        CollapseLeft,
        [Style("icon-collapse-right")]
        CollapseRight,
        [Style("icon-collapse-up")]
        CollapseUp,
        [Style("icon-cross")]
        Cross,
        [Style("icon-delete")]
        Delete,
        [Style("icon-document")]
        Document,
        [Style("icon-download")]
        Download,
        [Style("icon-edit")]
        Edit,
        [Style("icon-error")]
        Error,
        [Style("icon-filter")]
        Filter,
        [Style("icon-folder")]
        Folder,
        [Style("icon-hamburger")]
        Hamburger,
        [Style("icon-home")]
        Home,
        [Style("icon-mail")]
        Mail,
        [Style("icon-info")]
        Info,
        [Style("icon-link-external")]
        LinkExternal,
        [Style("icon-list")]
        List,
        [Style("icon-magnifier")]
        Magnifier,
        [Style("icon-min")]
        Min,
        [Style("icon-plus")]
        Plus,
        [Style("icon-question")]
        Question,
        [Style("icon-secure")]
        Secure,
        [Style("icon-success")]
        Success,
        [Style("icon-upload")]
        Upload,
        [Style("icon-user")]
        User,
        [Style("icon-warning--alt")]
        WarningAlt,
        [Style("icon -warning")]
        Warning
    }
}
